import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/registry";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "카라멜라 홈페이지",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <html lang="ko">
        <body>
          {/* <Header /> */}
          {children}
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
